### ISSUE TITLE
v0.1.2 github downloadUrl error 

### ISSUE THREAD

**Issue by QingHui653** [fescar-group/fescar-docker#6]
wget https://github.com/alibaba/fescar/releases/download/v0.1.2/fescar-server-0.1.2.tar.gz -P /home
--2019-02-19 01:47:24--  https://github.com/alibaba/fescar/releases/download/v0.1.2/fescar-server-0.1.2.tar.gz
![image](https://user-images.githubusercontent.com/15207108/52984750-b5368d00-342b-11e9-85fe-26981ed6f2b3.png)

now this downloadUrl is `https://github.com/alibaba/fescar/releases/download/V0.1.2/fescar-server-0.1.2.tar.gz`

**Comment by slievrly** [comment]
@QingHui653 3ks
